### ISSUE TITLE
Error with Mod tuchelSweepPlus

### ISSUE THREAD

**Issue by tomy852** [oschuhm/FS22_ToolDisplay#7]
Hello, there is an Error in the Log when using the Mod: "FS22_tuchelSweepPlus590" together with ToolDisplay.
The Mod is from Creative Mesh on official Modhub.
Its not a major Error, the device is still working 😉

[log.txt](https://github.com/oschuhm/FS22_ToolDisplay/files/13196417/log.txt)

![tuchel](https://github.com/oschuhm/FS22_ToolDisplay/assets/51209411/36590b90-4fc2-4607-9e27-e4cd39270d00)

**Comment by oschuhm** [comment]
FS22_tuchelSweepPlus590 was loaded after tool display.
With FS22_tuchelSweepPlus590 there was a new spec. added which was unknown for tool display.
Workaround ... make sure that tool display gets loaded at the very end.
Changing the file name starting with "zzz..." is a workaround until I found a final solution.
fixed with version 0.0.4
